window.fakejson=[
    {
        "avatar_url": "https://1.gravatar.com/avatar/e68309f117985270285ade8082f4877d?d=https%3A%2F%2Fidenticons.github.com%2F6feb2ea646d37fd3ffdaf2fdc6f0c0d3.png", 
        "email": "<a class=\"email js-obfuscate-email\" data-email=\"%6a%61%6b%65%77%68%61%72%74%6f%6e%40%67%6d%61%69%6c%2e%63%6f%6d\" href=\"mailto:{email}\">{email}</a>", 
        "events_url": "https://api.github.com/users/JakeWharton/events{/privacy}", 
        "followers_url": "https://api.github.com/users/JakeWharton/followers", 
        "following_url": "https://api.github.com/users/JakeWharton/following{/other_user}", 
        "full-name": "Jake Wharton", 
        "gists_url": "https://api.github.com/users/JakeWharton/gists{/gist_id}", 
        "gravatar_id": "e68309f117985270285ade8082f4877d", 
        "html_url": "https://github.com/JakeWharton", 
        "id": 66577, 
        "languages": "Java, Shell, Python", 
        "login": "JakeWharton", 
        "organizations_url": "https://api.github.com/users/JakeWharton/orgs", 
        "received_events_url": "https://api.github.com/users/JakeWharton/received_events", 
        "repos_url": "https://api.github.com/users/JakeWharton/repos", 
        "score": 1, 
        "starred_url": "https://api.github.com/users/JakeWharton/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/JakeWharton/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/JakeWharton"
    }, 
    {
        "avatar_url": "https://1.gravatar.com/avatar/31dad7d0a23acf47a7394fddc52c7730?d=https%3A%2F%2Fidenticons.github.com%2F60eb3b69c63cc6f72f243c89df792469.png", 
        "events_url": "https://api.github.com/users/pahimar/events{/privacy}", 
        "followers_url": "https://api.github.com/users/pahimar/followers", 
        "following_url": "https://api.github.com/users/pahimar/following{/other_user}", 
        "gists_url": "https://api.github.com/users/pahimar/gists{/gist_id}", 
        "gravatar_id": "31dad7d0a23acf47a7394fddc52c7730", 
        "html_url": "https://github.com/pahimar", 
        "id": 1450090, 
        "languages": "Java", 
        "login": "pahimar", 
        "organizations_url": "https://api.github.com/users/pahimar/orgs", 
        "received_events_url": "https://api.github.com/users/pahimar/received_events", 
        "repos_url": "https://api.github.com/users/pahimar/repos", 
        "score": 1, 
        "starred_url": "https://api.github.com/users/pahimar/starred{/owner}{/repo}", 
        "subscriptions_url": "https://api.github.com/users/pahimar/subscriptions", 
        "type": "User", 
        "url": "https://api.github.com/users/pahimar"
    }
]
